### ISSUE TITLE
Armbian OpenBox should be the default DE

### ISSUE THREAD

**Issue by zezba9000** [mangopi-sbc/MQ-Pro#5]
XFCE takes up 500mb just for booting & its slow.
OpenBox is a much better option.

Also does the "MQ-Pro D1" have a GPU?

**Comment by smaeul** [comment]
No, the D1 chip does not contain a GPU. There is a G2D hardware block for 2D acceleration, but there is no driver or userspace API for it.

**Comment by zezba9000** [comment]
Ok thanks for the info. Wonder why Linux has no userspace API to target this hardware if the driver did exist.
